name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: flask-aks-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Decode Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig

    - name: Set Context and Deploy
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
        kubectl config use-context aksdemo-aks
        kubectl get nodes
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
