name: Build and Deploy to AKS

on:
  push:
    branches:
      - master  # or 'main' if that's your branch name
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: flask-aks-demo

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
